services:
  nginx:
    # build:
    #      context: ./docker
    #      dockerfile: dev.nginx.Dockerfile
    image: nginx:1.17-alpine
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf

  phpfpm:
#    build:
#      context: ./docker
#      dockerfile: dev.fpm.Dockerfile
    image: leoqbc/phpcustom:1.0.0
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456