services:
    php:
        image: "webdevops/php-nginx-dev:8.3-alpine"
        working_dir: "/app"
        volumes:
            - ".:/app"
        ports:
            - "8888:80"
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
            - PHP_DISPLAY_ERRORS=1
    mysql:
        image: "mysql:8.0.3"
        command: "--default-authentication-plugin=mysql_native_password"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_DATABASE: "my_bids"
